### ISSUE TITLE
How to delete all datas under root node.

### ISSUE THREAD

**Issue by GikkiAres** [WildDogTeam/demo-ios-drawing#2]
I want to delete all datas under root node,here is my code:
```
- (void)clearDatas {
    __weak __typeof(self) weakSelf;
     [[[self.wilddog queryOrderedByKey] queryLimitedToFirst:5] observeEventType:WDGDataEventTypeValue withBlock:^(WDGDataSnapshot *snapshot) {
         NSLog(@"%@",snapshot.value);
         NSEnumerator *children = snapshot.children;
         WDGDataSnapshot *next = children.nextObject;
         while (next) {
            [next.ref removeValue];
             next = children.nextObject;
         }
    }];
}
```
This is a button event,I want to delete 5 pieces of data every time I click the button.But the problem is,when I first click the button,the snapshot returned contains 5 pieces of data,and I can delete them correctly.
But after the first time,the snapshot returned  contains no data,the console shows:
```
2017-03-09 11:57:17.901947 Wilddog Drawing[5475:2673406] Not a valid path: / -> (null)
2017-03-09 11:57:17.902140 Wilddog Drawing[5475:2673406] (null)
```

So,there are two questions:
1 how to return correct data after first click.
2 I think deleting datas in this way is not elegant,is there a more convenient way to delete data under the root node?

**Comment by ainopara** [comment]
If you just want to delete all data on root path, then
```
[self.wilddog removeValue];
```
will do what you need.

If you want to delete first 5 snapshot every time you tap a button, this should works:
```
- (void)clearDatas {
    __weak __typeof(self) weakSelf;
     [[[self.wilddog queryOrderedByKey] queryLimitedToFirst:5] observeSingleEventOfType:WDGDataEventTypeValue withBlock:^(WDGDataSnapshot *snapshot) {
         NSLog(@"%@",snapshot.value);
         NSEnumerator *children = snapshot.children;
         WDGDataSnapshot *next = children.nextObject;
         while (next) {
            [next.ref removeValue];
             next = children.nextObject;
         }
    }];
}
```
Due to a bug in Wilddog Sync iOS SDK, this method will not work until you upgrade WilddogSync.framework to version 2.2.4 , which will be released soon.
Note: WilddogCore.framework should be upgraded to 2.0.8 at the same time.

**Comment by GikkiAres** [comment]
yeah, this method is enough.This method would remove all its child node.
`[self.wilddog removeValue];`
